Repository Oris482/Cub3d, pull requests merged in 2022-10, with the labels that each got.

#6 FEAT: draw floor and ceiling, check argv(include map format)
  .gitignore
  check_argv/EAST.png
  check_argv/Makefile
  check_argv/NORTH.png
  check_argv/SOUTH.png
  check_argv/WEST.png
  check_argv/check_argv.c
  check_argv/check_map_elements.c
  check_argv/check_map_elements_utils.c
  check_argv/check_texture_elements.c
  check_argv/check_texture_elements_utils.c
  check_argv/degree_utils.c
  check_argv/ft_string.h
  check_argv/get_next_line.c
  check_argv/get_next_line.h
  check_argv/get_next_line_utils.c
  check_argv/main.c
  check_argv/make_ceiling_floor_image.c
  check_argv/path_to_the_east_texture
  check_argv/path_to_the_north_texture
  check_argv/path_to_the_south_texture
  check_argv/path_to_the_west_texture
  check_argv/print_functions.c
  check_argv/rgb_utils.c
  check_argv/sample_map.cub
  check_argv/string_utils.c
  check_argv/utils.c
  cub3d.h
  make_ceiling_floor/Makefile
  make_ceiling_floor/degree_utils.c
  make_ceiling_floor/main.c
  make_ceiling_floor/make_ceiling_floor_image.c
  mlx/Makefile
  mlx/font.c
  mlx/interface.swift
  mlx/man/man3/mlx.3
  mlx/man/man3/mlx_loop.3
  mlx/man/man3/mlx_new_image.3
  mlx/man/man3/mlx_new_window.3
  mlx/man/man3/mlx_pixel_put.3
  mlx/mlx.h
  mlx/mlx_image.swift
  mlx/mlx_init.swift
  mlx/mlx_png.c
  mlx/mlx_rgb.c
  mlx/mlx_string_put.c
  mlx/mlx_window.swift
  mlx/mlx_xpm.c
Labels: FEAT

#20 Feat display texture#17
  Makefile
  check_texture_elements.c
  cub3d.h
  display_texture.c
  main.c
  print_functions.c
  ray_casting.c
Labels: FEAT

#22 bug: adjust player position on minimap #18
  draw_minimap.c
Labels: ENHANCEMENT

#25 Feat rotate view mouse#24
  check_map_elements.c
  cub3d.h
  draw_minimap.c
  handle_player.c
  main.c
  print_functions.c
  ray_casting.c
Labels: FEAT

#27 FIX: Sync minimap ray with fov_h
  draw_minimap.c
Labels: BUG

#30 Feat far wall dark#26
  check_texture_elements.c
  cub3d.h
  display_texture.c
  draw_minimap.c
  main.c
  make_ceiling_floor_image.c
  make_minimap_image.c
  path_to_the_east_texture
  path_to_the_north_texture
  path_to_the_south_texture
  path_to_the_west_texture
  ray_casting.c
  sample_map.cub
  texture/EAST.png
  texture/NORTH.png
  texture/SOUTH.png
  texture/WEST.png
  texture/black_wall.png
  utils.c
Labels: FEAT

#31 ENHANCEMENT: make easy to turn cardinal points
  cub3d.h
  main.c
Labels: ENHANCEMENT

#32 Feat mouse onoff#28
  cub3d.h
  handle_player.c
  main.c
Labels: FEAT

#34 Feat boost key#33
  cub3d.h
  display_texture.c
  handle_player.c
  main.c
  ray_casting.c
Labels: FEAT
